---
apiVersion: v1
kind: Route
metadata:
  name: "${project.artifactId}-svc-swagger"
  creationTimestamp:
  labels:
    app: "${project.artifactId}"
    provider: fabric8
    version: "${project.version}"
    group: "${project.groupId}"
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  host: camel-kafka-vr-svc-strimzi.app.88.198.65.4.nip.io
  path: "/webjars/swagger-ui/2.1.0/index.html?url=/camel/api-docs"
  to:
    kind: Service
    name: "${project.artifactId}-svc"
  port:
    targetPort: http
status: {}